### ISSUE TITLE
[Bug] Control Ordering of Keys when JSON Marshaling the `Order` Field

### ISSUE THREAD

**Issue by acham1** [TernaryInc/cubejs-go#1]
According to the [cubejs docs](https://cube.dev/docs/query-format), the `Order` field on the query model has this behavior: 

> an object, where the keys are measures or dimensions to order by and their corresponding values are either asc or desc. The order of the fields to order on is based on the order of the keys in the object.

<img width="651" alt="Screen Shot 2022-07-26 at 12 57 12 PM" src="https://user-images.githubusercontent.com/13604807/181066022-abf66c60-8910-4b36-9faf-424eb70f1f99.png">

However, this client currently models the Order field as a simple `map[string]string`. When JSON marshaling such a map, golang does not guarantee any particular order of keys in the output document. This can cause unexpected and incorrect behavior when requesting results to be ordered by multiple keys in a particular priority.

**Comment by brucesw** [comment]
See https://github.com/TernaryInc/cubejs-go/pull/3/files

**Comment by acham1** [comment]
Resolved in #3
