### ISSUE TITLE
Error during unmarshal of query results when measure value is number but cubejs returns string value

### ISSUE THREAD

**Issue by jondysinger** [TernaryInc/cubejs-go#5]
When I test the `TestLocalServer` function in example.go, I'm getting the following error:
```
2022/12/18 17:59:57 load query: unmarshal load response data: []main.QueryResult: main.QueryResult.Cost: readNumberAsString: invalid number, error found in #10 byte of ...|measure1":"5687.23"}
```

I believe this is because the json that cubejs is returning has quotes around numbers. Here is an example of the test data returned from cubejs:
```json
"data": [
  {
    "MyCube.dimension1": "P1",
    "MyCube.measure1": "5687.23",
    "MyCube.timestamp": "2022-04-05T00:00:00.000",
    "MyCube.timestamp.day": "2022-04-05T00:00:00.000"
  }
]
```

The struct for the query results has `MyCube.measure1` defined as a `float64`.
```go
type QueryResult struct {
  Cost float64 `json:"MyCube.measure1"`
  ProjectID string `json:"MyCube.dimension1"`
  Timestamp time.Time `json:"MyCube.timestamp"`
}
```

If I change that struct so that `Cost` is a `string`, the error goes away. However, I'm left with a `string` instead of a `float64` and have to do a conversion.

A little info about my environment:
- I am running cubejs from a docker container based on the [cubejs/cube](https://hub.docker.com/r/cubejs/cube) image from docker hub.
- That cubejs instance is connecting to a postgres database on the host machine (via host.docker.internal).

From the [cubejs API reference](https://cube.dev/docs/rest-api#api-reference), it looks like it's by design to have the numbers returned in json as strings:
> Currently all fetched numericals are returned in the same format as driver returns it without any additional processing. Most of drivers return numerical values as strings instead of javascript integer or float to ensure there's no loss of significance. Client code should take care of parsing such numerical values.

The standard library `json.Unmarshal` doesn't have a problem converting the json number string values to `float64`. However, it complains about the date format (hence the usage of `jsontime.Unmarshal` with `ConfigWithCustomTimeFormat`).
```
2022/12/18 18:42:55 load query: unmarshal load response data: parsing time "\"2022-04-05T00:00:00.000\"" as "\"2006-01-02T15:04:05Z07:00\"": cannot parse "\"" as "Z07:00"
```

Is there something perhaps I'm missing? It seems the only options are:
1. Define the measure as a `string` in the struct and then convert it after the values are returned from `cubeClient.Load`.
2. Programmatically modify the json in the `responseBody.Data` to remove the quotes around number values before it is unmarshalled.
3. Use the standard `json.Unmarshal` but implement the `json.Marshaler` / `json.Unmarshaler` interfaces on a custom date type per this [SO answer](https://stackoverflow.com/a/25088283/6130076).

**Comment by acham1** [comment]
Hi @jondysinger,

The options you listed all seem like fine possibilities to me, but come with some compromises. Before reaching for those, would you be interested to try this instead?

i.e. 

```
type QueryResult struct {
  Cost float64 `json:"MyCube.measure1,string"` // notice the new "string" option in the JSON tag
  ...
}
```

More info can be found [here](https://pkg.go.dev/encoding/json#Marshal)

> The "string" option signals that a field is stored as JSON inside a JSON-encoded string. It applies only to fields of string, floating point, integer, or boolean types. 

Let me know your thoughts; thanks!

**Comment by jondysinger** [comment]
I retried it with your suggestion, @acham1, and it worked great! Thanks for the tip!

**Comment by acham1** [comment]
That's great to hear; thank you for trying our library and uncovering this interesting case.
